---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Check sysctl for net.ipv6.conf.all.disable_ipv6
      ansible.posix.sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        value: '1'
      # checkmode: true
